### ISSUE TITLE
It should get compiling error, the compileSdkVersion should be 26 or higher

### ISSUE THREAD

**Issue by csytang** [jbvincey/InstantAppSample#1]
Hi, jbvincey, the compileSdkVersion in the build.gradle is set to 25, but when I run this code on my Android Studio, it shows that feature modules requires compileSdkVersion to 26.

But when you change the compileSdKversion to 26, still you cannot go through the Google Play Console to publish the instant app.

Any suggestions?
please also contact me at chris.yttang(AT)hotmail.com if possible. best

**Comment by florent37** [comment]
can you send a screenshot ?

**Comment by csytang** [comment]
<img width="611" alt="2017-09-14 4 15 09" src="https://user-images.githubusercontent.com/10499238/30419158-f1583e42-9967-11e7-9a31-2f177277169a.png">
Please see the configuration in project. I also use the setting the reps. still this problem
IDE: Android Studio 3.0 Beta

**Comment by csytang** [comment]
You will meet this problem in multiple-feature instant app

**Comment by florent37** [comment]
Set the compilesdk to 26 too

**Comment by csytang** [comment]
Set the compileSDK to 26, you will not get any compiling error. But when you try to publish on Google Play, you will find an error "ensure that the APKs with version code ? have the android:targetSandboxVersion attribute set to '2' in the AndroidManifest.xml"

**Comment by jbvincey** [comment]
The actual compileSdkVersion is 26 and should stay like this. The attribute _targetSandboxVersion_ is required for Android O, and should be automatically added by Android Studio. But apparently it is not, I think this is a bug from Android Studio. However you can add it manually in the base feature manifest. In the manifest element, just add:
`android:targetSandboxVersion="2"`

I would recommend creating a new application if you want to release in production (although development mode is OK), this one is already available on the Play Store [here](https://play.google.com/store/apps/details?id=com.jbvincey.instanttripdemo) and as instant app:
- [list of trips](https://jbvincey.com/instanttripdemo/trips/)
- [trip details](https://jbvincey.com/instanttripdemo/trips/8399271233)

I will add soon the major release issues on the readme.
